package config

import (
	"encoding/json"

	"github.com/mylxsw/glacier/infra"
)

type Config struct {
	{{- if eq .WithHttpServer "Y" }}
	Listen string `json:"listen"`
	{{ if eq .WithSessionSupport "Y"}}SessionKey string `json:"session_key"`{{ end }}
	{{ end }}
}

func (conf *Config) Serialize() string {
	rs, _ := json.Marshal(conf)
	return string(rs)
}

// Get return config object from container
func Get(cc infra.Resolver) *Config {
	return cc.MustGet(&Config{}).(*Config)
}
